spring:
  batch:
    job:
      names: ${JOB_NAME:NONE}
    jdbc:
      initialize-schema: always
  h2:
    console:
      enabled: true
  profiles:
    active: local
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
    url: ${JDBC_URL}

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
      format_sql: true
      show_sql: true
      dialect: org.hibernate.dialect.H2Dialect

jandi:
  progressBotUrl: ${JANDI_PROGRESS_BOT_URL}
  changedBotUrl: ${JANDI_CHANGED_BOT_URL}
jira:
  baseURI: ${JIRA_BASEURI}
  username: ${JIRA_USERNAME}
  token: ${JIRA_TOKEN}

server:
  port: 8081